// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClassesColumns holds the columns for the "classes" table.
	ClassesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "class_name", Type: field.TypeString},
		{Name: "f1", Type: field.TypeString, Default: ""},
		{Name: "f2", Type: field.TypeString, Default: ""},
		{Name: "f3", Type: field.TypeString, Default: ""},
		{Name: "f4", Type: field.TypeString, Default: ""},
		{Name: "f5", Type: field.TypeString, Default: ""},
		{Name: "f6", Type: field.TypeString, Default: ""},
		{Name: "f7", Type: field.TypeString, Default: ""},
		{Name: "f8", Type: field.TypeString, Default: ""},
		{Name: "f9", Type: field.TypeString, Default: ""},
		{Name: "f10", Type: field.TypeString, Default: ""},
		{Name: "f11", Type: field.TypeString, Default: ""},
		{Name: "f12", Type: field.TypeString, Default: ""},
		{Name: "f13", Type: field.TypeString, Default: ""},
		{Name: "f14", Type: field.TypeString, Default: ""},
		{Name: "f15", Type: field.TypeString, Default: ""},
		{Name: "f16", Type: field.TypeString, Default: ""},
		{Name: "f17", Type: field.TypeString, Default: ""},
		{Name: "f18", Type: field.TypeString, Default: ""},
		{Name: "f19", Type: field.TypeString, Default: ""},
		{Name: "f20", Type: field.TypeString, Default: ""},
		{Name: "f21", Type: field.TypeString, Default: ""},
		{Name: "f22", Type: field.TypeString, Default: ""},
	}
	// ClassesTable holds the schema information for the "classes" table.
	ClassesTable = &schema.Table{
		Name:       "classes",
		Columns:    ClassesColumns,
		PrimaryKey: []*schema.Column{ClassesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "nick_name", Type: field.TypeString, Default: ""},
		{Name: "f1", Type: field.TypeString, Default: ""},
		{Name: "f2", Type: field.TypeString, Default: ""},
		{Name: "f3", Type: field.TypeString, Default: ""},
		{Name: "f4", Type: field.TypeString, Default: ""},
		{Name: "f5", Type: field.TypeString, Default: ""},
		{Name: "f6", Type: field.TypeString, Default: ""},
		{Name: "f7", Type: field.TypeString, Default: ""},
		{Name: "f8", Type: field.TypeString, Default: ""},
		{Name: "f9", Type: field.TypeString, Default: ""},
		{Name: "f10", Type: field.TypeString, Default: ""},
		{Name: "f11", Type: field.TypeString, Default: ""},
		{Name: "f12", Type: field.TypeString, Default: ""},
		{Name: "f13", Type: field.TypeString, Default: ""},
		{Name: "f14", Type: field.TypeString, Default: ""},
		{Name: "f15", Type: field.TypeString, Default: ""},
		{Name: "f16", Type: field.TypeString, Default: ""},
		{Name: "f17", Type: field.TypeString, Default: ""},
		{Name: "f18", Type: field.TypeString, Default: ""},
		{Name: "f19", Type: field.TypeString, Default: ""},
		{Name: "f20", Type: field.TypeString, Default: ""},
		{Name: "f21", Type: field.TypeString, Default: ""},
		{Name: "f22", Type: field.TypeString, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClassesTable,
		UsersTable,
	}
)

func init() {
}
