// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/danielhookx/go_skill/exercise/ent/ent/class"
	"github.com/danielhookx/go_skill/exercise/ent/ent/user"
	"github.com/danielhookx/go_skill/exercise/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	classFields := schema.Class{}.Fields()
	_ = classFields
	// classDescF1 is the schema descriptor for f1 field.
	classDescF1 := classFields[2].Descriptor()
	// class.DefaultF1 holds the default value on creation for the f1 field.
	class.DefaultF1 = classDescF1.Default.(string)
	// classDescF2 is the schema descriptor for f2 field.
	classDescF2 := classFields[3].Descriptor()
	// class.DefaultF2 holds the default value on creation for the f2 field.
	class.DefaultF2 = classDescF2.Default.(string)
	// classDescF3 is the schema descriptor for f3 field.
	classDescF3 := classFields[4].Descriptor()
	// class.DefaultF3 holds the default value on creation for the f3 field.
	class.DefaultF3 = classDescF3.Default.(string)
	// classDescF4 is the schema descriptor for f4 field.
	classDescF4 := classFields[5].Descriptor()
	// class.DefaultF4 holds the default value on creation for the f4 field.
	class.DefaultF4 = classDescF4.Default.(string)
	// classDescF5 is the schema descriptor for f5 field.
	classDescF5 := classFields[6].Descriptor()
	// class.DefaultF5 holds the default value on creation for the f5 field.
	class.DefaultF5 = classDescF5.Default.(string)
	// classDescF6 is the schema descriptor for f6 field.
	classDescF6 := classFields[7].Descriptor()
	// class.DefaultF6 holds the default value on creation for the f6 field.
	class.DefaultF6 = classDescF6.Default.(string)
	// classDescF7 is the schema descriptor for f7 field.
	classDescF7 := classFields[8].Descriptor()
	// class.DefaultF7 holds the default value on creation for the f7 field.
	class.DefaultF7 = classDescF7.Default.(string)
	// classDescF8 is the schema descriptor for f8 field.
	classDescF8 := classFields[9].Descriptor()
	// class.DefaultF8 holds the default value on creation for the f8 field.
	class.DefaultF8 = classDescF8.Default.(string)
	// classDescF9 is the schema descriptor for f9 field.
	classDescF9 := classFields[10].Descriptor()
	// class.DefaultF9 holds the default value on creation for the f9 field.
	class.DefaultF9 = classDescF9.Default.(string)
	// classDescF10 is the schema descriptor for f10 field.
	classDescF10 := classFields[11].Descriptor()
	// class.DefaultF10 holds the default value on creation for the f10 field.
	class.DefaultF10 = classDescF10.Default.(string)
	// classDescF11 is the schema descriptor for f11 field.
	classDescF11 := classFields[12].Descriptor()
	// class.DefaultF11 holds the default value on creation for the f11 field.
	class.DefaultF11 = classDescF11.Default.(string)
	// classDescF12 is the schema descriptor for f12 field.
	classDescF12 := classFields[13].Descriptor()
	// class.DefaultF12 holds the default value on creation for the f12 field.
	class.DefaultF12 = classDescF12.Default.(string)
	// classDescF13 is the schema descriptor for f13 field.
	classDescF13 := classFields[14].Descriptor()
	// class.DefaultF13 holds the default value on creation for the f13 field.
	class.DefaultF13 = classDescF13.Default.(string)
	// classDescF14 is the schema descriptor for f14 field.
	classDescF14 := classFields[15].Descriptor()
	// class.DefaultF14 holds the default value on creation for the f14 field.
	class.DefaultF14 = classDescF14.Default.(string)
	// classDescF15 is the schema descriptor for f15 field.
	classDescF15 := classFields[16].Descriptor()
	// class.DefaultF15 holds the default value on creation for the f15 field.
	class.DefaultF15 = classDescF15.Default.(string)
	// classDescF16 is the schema descriptor for f16 field.
	classDescF16 := classFields[17].Descriptor()
	// class.DefaultF16 holds the default value on creation for the f16 field.
	class.DefaultF16 = classDescF16.Default.(string)
	// classDescF17 is the schema descriptor for f17 field.
	classDescF17 := classFields[18].Descriptor()
	// class.DefaultF17 holds the default value on creation for the f17 field.
	class.DefaultF17 = classDescF17.Default.(string)
	// classDescF18 is the schema descriptor for f18 field.
	classDescF18 := classFields[19].Descriptor()
	// class.DefaultF18 holds the default value on creation for the f18 field.
	class.DefaultF18 = classDescF18.Default.(string)
	// classDescF19 is the schema descriptor for f19 field.
	classDescF19 := classFields[20].Descriptor()
	// class.DefaultF19 holds the default value on creation for the f19 field.
	class.DefaultF19 = classDescF19.Default.(string)
	// classDescF20 is the schema descriptor for f20 field.
	classDescF20 := classFields[21].Descriptor()
	// class.DefaultF20 holds the default value on creation for the f20 field.
	class.DefaultF20 = classDescF20.Default.(string)
	// classDescF21 is the schema descriptor for f21 field.
	classDescF21 := classFields[22].Descriptor()
	// class.DefaultF21 holds the default value on creation for the f21 field.
	class.DefaultF21 = classDescF21.Default.(string)
	// classDescF22 is the schema descriptor for f22 field.
	classDescF22 := classFields[23].Descriptor()
	// class.DefaultF22 holds the default value on creation for the f22 field.
	class.DefaultF22 = classDescF22.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickName is the schema descriptor for nick_name field.
	userDescNickName := userFields[1].Descriptor()
	// user.DefaultNickName holds the default value on creation for the nick_name field.
	user.DefaultNickName = userDescNickName.Default.(string)
	// userDescF1 is the schema descriptor for f1 field.
	userDescF1 := userFields[2].Descriptor()
	// user.DefaultF1 holds the default value on creation for the f1 field.
	user.DefaultF1 = userDescF1.Default.(string)
	// userDescF2 is the schema descriptor for f2 field.
	userDescF2 := userFields[3].Descriptor()
	// user.DefaultF2 holds the default value on creation for the f2 field.
	user.DefaultF2 = userDescF2.Default.(string)
	// userDescF3 is the schema descriptor for f3 field.
	userDescF3 := userFields[4].Descriptor()
	// user.DefaultF3 holds the default value on creation for the f3 field.
	user.DefaultF3 = userDescF3.Default.(string)
	// userDescF4 is the schema descriptor for f4 field.
	userDescF4 := userFields[5].Descriptor()
	// user.DefaultF4 holds the default value on creation for the f4 field.
	user.DefaultF4 = userDescF4.Default.(string)
	// userDescF5 is the schema descriptor for f5 field.
	userDescF5 := userFields[6].Descriptor()
	// user.DefaultF5 holds the default value on creation for the f5 field.
	user.DefaultF5 = userDescF5.Default.(string)
	// userDescF6 is the schema descriptor for f6 field.
	userDescF6 := userFields[7].Descriptor()
	// user.DefaultF6 holds the default value on creation for the f6 field.
	user.DefaultF6 = userDescF6.Default.(string)
	// userDescF7 is the schema descriptor for f7 field.
	userDescF7 := userFields[8].Descriptor()
	// user.DefaultF7 holds the default value on creation for the f7 field.
	user.DefaultF7 = userDescF7.Default.(string)
	// userDescF8 is the schema descriptor for f8 field.
	userDescF8 := userFields[9].Descriptor()
	// user.DefaultF8 holds the default value on creation for the f8 field.
	user.DefaultF8 = userDescF8.Default.(string)
	// userDescF9 is the schema descriptor for f9 field.
	userDescF9 := userFields[10].Descriptor()
	// user.DefaultF9 holds the default value on creation for the f9 field.
	user.DefaultF9 = userDescF9.Default.(string)
	// userDescF10 is the schema descriptor for f10 field.
	userDescF10 := userFields[11].Descriptor()
	// user.DefaultF10 holds the default value on creation for the f10 field.
	user.DefaultF10 = userDescF10.Default.(string)
	// userDescF11 is the schema descriptor for f11 field.
	userDescF11 := userFields[12].Descriptor()
	// user.DefaultF11 holds the default value on creation for the f11 field.
	user.DefaultF11 = userDescF11.Default.(string)
	// userDescF12 is the schema descriptor for f12 field.
	userDescF12 := userFields[13].Descriptor()
	// user.DefaultF12 holds the default value on creation for the f12 field.
	user.DefaultF12 = userDescF12.Default.(string)
	// userDescF13 is the schema descriptor for f13 field.
	userDescF13 := userFields[14].Descriptor()
	// user.DefaultF13 holds the default value on creation for the f13 field.
	user.DefaultF13 = userDescF13.Default.(string)
	// userDescF14 is the schema descriptor for f14 field.
	userDescF14 := userFields[15].Descriptor()
	// user.DefaultF14 holds the default value on creation for the f14 field.
	user.DefaultF14 = userDescF14.Default.(string)
	// userDescF15 is the schema descriptor for f15 field.
	userDescF15 := userFields[16].Descriptor()
	// user.DefaultF15 holds the default value on creation for the f15 field.
	user.DefaultF15 = userDescF15.Default.(string)
	// userDescF16 is the schema descriptor for f16 field.
	userDescF16 := userFields[17].Descriptor()
	// user.DefaultF16 holds the default value on creation for the f16 field.
	user.DefaultF16 = userDescF16.Default.(string)
	// userDescF17 is the schema descriptor for f17 field.
	userDescF17 := userFields[18].Descriptor()
	// user.DefaultF17 holds the default value on creation for the f17 field.
	user.DefaultF17 = userDescF17.Default.(string)
	// userDescF18 is the schema descriptor for f18 field.
	userDescF18 := userFields[19].Descriptor()
	// user.DefaultF18 holds the default value on creation for the f18 field.
	user.DefaultF18 = userDescF18.Default.(string)
	// userDescF19 is the schema descriptor for f19 field.
	userDescF19 := userFields[20].Descriptor()
	// user.DefaultF19 holds the default value on creation for the f19 field.
	user.DefaultF19 = userDescF19.Default.(string)
	// userDescF20 is the schema descriptor for f20 field.
	userDescF20 := userFields[21].Descriptor()
	// user.DefaultF20 holds the default value on creation for the f20 field.
	user.DefaultF20 = userDescF20.Default.(string)
	// userDescF21 is the schema descriptor for f21 field.
	userDescF21 := userFields[22].Descriptor()
	// user.DefaultF21 holds the default value on creation for the f21 field.
	user.DefaultF21 = userDescF21.Default.(string)
	// userDescF22 is the schema descriptor for f22 field.
	userDescF22 := userFields[23].Descriptor()
	// user.DefaultF22 holds the default value on creation for the f22 field.
	user.DefaultF22 = userDescF22.Default.(string)
}
