// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danielhookx/go_skill/exercise/ent/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (uc *UserCreate) SetName(s string) *UserCreate {
	uc.mutation.SetName(s)
	return uc
}

// SetNickName sets the "nick_name" field.
func (uc *UserCreate) SetNickName(s string) *UserCreate {
	uc.mutation.SetNickName(s)
	return uc
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (uc *UserCreate) SetNillableNickName(s *string) *UserCreate {
	if s != nil {
		uc.SetNickName(*s)
	}
	return uc
}

// SetF1 sets the "f1" field.
func (uc *UserCreate) SetF1(s string) *UserCreate {
	uc.mutation.SetF1(s)
	return uc
}

// SetNillableF1 sets the "f1" field if the given value is not nil.
func (uc *UserCreate) SetNillableF1(s *string) *UserCreate {
	if s != nil {
		uc.SetF1(*s)
	}
	return uc
}

// SetF2 sets the "f2" field.
func (uc *UserCreate) SetF2(s string) *UserCreate {
	uc.mutation.SetF2(s)
	return uc
}

// SetNillableF2 sets the "f2" field if the given value is not nil.
func (uc *UserCreate) SetNillableF2(s *string) *UserCreate {
	if s != nil {
		uc.SetF2(*s)
	}
	return uc
}

// SetF3 sets the "f3" field.
func (uc *UserCreate) SetF3(s string) *UserCreate {
	uc.mutation.SetF3(s)
	return uc
}

// SetNillableF3 sets the "f3" field if the given value is not nil.
func (uc *UserCreate) SetNillableF3(s *string) *UserCreate {
	if s != nil {
		uc.SetF3(*s)
	}
	return uc
}

// SetF4 sets the "f4" field.
func (uc *UserCreate) SetF4(s string) *UserCreate {
	uc.mutation.SetF4(s)
	return uc
}

// SetNillableF4 sets the "f4" field if the given value is not nil.
func (uc *UserCreate) SetNillableF4(s *string) *UserCreate {
	if s != nil {
		uc.SetF4(*s)
	}
	return uc
}

// SetF5 sets the "f5" field.
func (uc *UserCreate) SetF5(s string) *UserCreate {
	uc.mutation.SetF5(s)
	return uc
}

// SetNillableF5 sets the "f5" field if the given value is not nil.
func (uc *UserCreate) SetNillableF5(s *string) *UserCreate {
	if s != nil {
		uc.SetF5(*s)
	}
	return uc
}

// SetF6 sets the "f6" field.
func (uc *UserCreate) SetF6(s string) *UserCreate {
	uc.mutation.SetF6(s)
	return uc
}

// SetNillableF6 sets the "f6" field if the given value is not nil.
func (uc *UserCreate) SetNillableF6(s *string) *UserCreate {
	if s != nil {
		uc.SetF6(*s)
	}
	return uc
}

// SetF7 sets the "f7" field.
func (uc *UserCreate) SetF7(s string) *UserCreate {
	uc.mutation.SetF7(s)
	return uc
}

// SetNillableF7 sets the "f7" field if the given value is not nil.
func (uc *UserCreate) SetNillableF7(s *string) *UserCreate {
	if s != nil {
		uc.SetF7(*s)
	}
	return uc
}

// SetF8 sets the "f8" field.
func (uc *UserCreate) SetF8(s string) *UserCreate {
	uc.mutation.SetF8(s)
	return uc
}

// SetNillableF8 sets the "f8" field if the given value is not nil.
func (uc *UserCreate) SetNillableF8(s *string) *UserCreate {
	if s != nil {
		uc.SetF8(*s)
	}
	return uc
}

// SetF9 sets the "f9" field.
func (uc *UserCreate) SetF9(s string) *UserCreate {
	uc.mutation.SetF9(s)
	return uc
}

// SetNillableF9 sets the "f9" field if the given value is not nil.
func (uc *UserCreate) SetNillableF9(s *string) *UserCreate {
	if s != nil {
		uc.SetF9(*s)
	}
	return uc
}

// SetF10 sets the "f10" field.
func (uc *UserCreate) SetF10(s string) *UserCreate {
	uc.mutation.SetF10(s)
	return uc
}

// SetNillableF10 sets the "f10" field if the given value is not nil.
func (uc *UserCreate) SetNillableF10(s *string) *UserCreate {
	if s != nil {
		uc.SetF10(*s)
	}
	return uc
}

// SetF11 sets the "f11" field.
func (uc *UserCreate) SetF11(s string) *UserCreate {
	uc.mutation.SetF11(s)
	return uc
}

// SetNillableF11 sets the "f11" field if the given value is not nil.
func (uc *UserCreate) SetNillableF11(s *string) *UserCreate {
	if s != nil {
		uc.SetF11(*s)
	}
	return uc
}

// SetF12 sets the "f12" field.
func (uc *UserCreate) SetF12(s string) *UserCreate {
	uc.mutation.SetF12(s)
	return uc
}

// SetNillableF12 sets the "f12" field if the given value is not nil.
func (uc *UserCreate) SetNillableF12(s *string) *UserCreate {
	if s != nil {
		uc.SetF12(*s)
	}
	return uc
}

// SetF13 sets the "f13" field.
func (uc *UserCreate) SetF13(s string) *UserCreate {
	uc.mutation.SetF13(s)
	return uc
}

// SetNillableF13 sets the "f13" field if the given value is not nil.
func (uc *UserCreate) SetNillableF13(s *string) *UserCreate {
	if s != nil {
		uc.SetF13(*s)
	}
	return uc
}

// SetF14 sets the "f14" field.
func (uc *UserCreate) SetF14(s string) *UserCreate {
	uc.mutation.SetF14(s)
	return uc
}

// SetNillableF14 sets the "f14" field if the given value is not nil.
func (uc *UserCreate) SetNillableF14(s *string) *UserCreate {
	if s != nil {
		uc.SetF14(*s)
	}
	return uc
}

// SetF15 sets the "f15" field.
func (uc *UserCreate) SetF15(s string) *UserCreate {
	uc.mutation.SetF15(s)
	return uc
}

// SetNillableF15 sets the "f15" field if the given value is not nil.
func (uc *UserCreate) SetNillableF15(s *string) *UserCreate {
	if s != nil {
		uc.SetF15(*s)
	}
	return uc
}

// SetF16 sets the "f16" field.
func (uc *UserCreate) SetF16(s string) *UserCreate {
	uc.mutation.SetF16(s)
	return uc
}

// SetNillableF16 sets the "f16" field if the given value is not nil.
func (uc *UserCreate) SetNillableF16(s *string) *UserCreate {
	if s != nil {
		uc.SetF16(*s)
	}
	return uc
}

// SetF17 sets the "f17" field.
func (uc *UserCreate) SetF17(s string) *UserCreate {
	uc.mutation.SetF17(s)
	return uc
}

// SetNillableF17 sets the "f17" field if the given value is not nil.
func (uc *UserCreate) SetNillableF17(s *string) *UserCreate {
	if s != nil {
		uc.SetF17(*s)
	}
	return uc
}

// SetF18 sets the "f18" field.
func (uc *UserCreate) SetF18(s string) *UserCreate {
	uc.mutation.SetF18(s)
	return uc
}

// SetNillableF18 sets the "f18" field if the given value is not nil.
func (uc *UserCreate) SetNillableF18(s *string) *UserCreate {
	if s != nil {
		uc.SetF18(*s)
	}
	return uc
}

// SetF19 sets the "f19" field.
func (uc *UserCreate) SetF19(s string) *UserCreate {
	uc.mutation.SetF19(s)
	return uc
}

// SetNillableF19 sets the "f19" field if the given value is not nil.
func (uc *UserCreate) SetNillableF19(s *string) *UserCreate {
	if s != nil {
		uc.SetF19(*s)
	}
	return uc
}

// SetF20 sets the "f20" field.
func (uc *UserCreate) SetF20(s string) *UserCreate {
	uc.mutation.SetF20(s)
	return uc
}

// SetNillableF20 sets the "f20" field if the given value is not nil.
func (uc *UserCreate) SetNillableF20(s *string) *UserCreate {
	if s != nil {
		uc.SetF20(*s)
	}
	return uc
}

// SetF21 sets the "f21" field.
func (uc *UserCreate) SetF21(s string) *UserCreate {
	uc.mutation.SetF21(s)
	return uc
}

// SetNillableF21 sets the "f21" field if the given value is not nil.
func (uc *UserCreate) SetNillableF21(s *string) *UserCreate {
	if s != nil {
		uc.SetF21(*s)
	}
	return uc
}

// SetF22 sets the "f22" field.
func (uc *UserCreate) SetF22(s string) *UserCreate {
	uc.mutation.SetF22(s)
	return uc
}

// SetNillableF22 sets the "f22" field if the given value is not nil.
func (uc *UserCreate) SetNillableF22(s *string) *UserCreate {
	if s != nil {
		uc.SetF22(*s)
	}
	return uc
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UserCreate) defaults() {
	if _, ok := uc.mutation.NickName(); !ok {
		v := user.DefaultNickName
		uc.mutation.SetNickName(v)
	}
	if _, ok := uc.mutation.F1(); !ok {
		v := user.DefaultF1
		uc.mutation.SetF1(v)
	}
	if _, ok := uc.mutation.F2(); !ok {
		v := user.DefaultF2
		uc.mutation.SetF2(v)
	}
	if _, ok := uc.mutation.F3(); !ok {
		v := user.DefaultF3
		uc.mutation.SetF3(v)
	}
	if _, ok := uc.mutation.F4(); !ok {
		v := user.DefaultF4
		uc.mutation.SetF4(v)
	}
	if _, ok := uc.mutation.F5(); !ok {
		v := user.DefaultF5
		uc.mutation.SetF5(v)
	}
	if _, ok := uc.mutation.F6(); !ok {
		v := user.DefaultF6
		uc.mutation.SetF6(v)
	}
	if _, ok := uc.mutation.F7(); !ok {
		v := user.DefaultF7
		uc.mutation.SetF7(v)
	}
	if _, ok := uc.mutation.F8(); !ok {
		v := user.DefaultF8
		uc.mutation.SetF8(v)
	}
	if _, ok := uc.mutation.F9(); !ok {
		v := user.DefaultF9
		uc.mutation.SetF9(v)
	}
	if _, ok := uc.mutation.F10(); !ok {
		v := user.DefaultF10
		uc.mutation.SetF10(v)
	}
	if _, ok := uc.mutation.F11(); !ok {
		v := user.DefaultF11
		uc.mutation.SetF11(v)
	}
	if _, ok := uc.mutation.F12(); !ok {
		v := user.DefaultF12
		uc.mutation.SetF12(v)
	}
	if _, ok := uc.mutation.F13(); !ok {
		v := user.DefaultF13
		uc.mutation.SetF13(v)
	}
	if _, ok := uc.mutation.F14(); !ok {
		v := user.DefaultF14
		uc.mutation.SetF14(v)
	}
	if _, ok := uc.mutation.F15(); !ok {
		v := user.DefaultF15
		uc.mutation.SetF15(v)
	}
	if _, ok := uc.mutation.F16(); !ok {
		v := user.DefaultF16
		uc.mutation.SetF16(v)
	}
	if _, ok := uc.mutation.F17(); !ok {
		v := user.DefaultF17
		uc.mutation.SetF17(v)
	}
	if _, ok := uc.mutation.F18(); !ok {
		v := user.DefaultF18
		uc.mutation.SetF18(v)
	}
	if _, ok := uc.mutation.F19(); !ok {
		v := user.DefaultF19
		uc.mutation.SetF19(v)
	}
	if _, ok := uc.mutation.F20(); !ok {
		v := user.DefaultF20
		uc.mutation.SetF20(v)
	}
	if _, ok := uc.mutation.F21(); !ok {
		v := user.DefaultF21
		uc.mutation.SetF21(v)
	}
	if _, ok := uc.mutation.F22(); !ok {
		v := user.DefaultF22
		uc.mutation.SetF22(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if _, ok := uc.mutation.NickName(); !ok {
		return &ValidationError{Name: "nick_name", err: errors.New(`ent: missing required field "User.nick_name"`)}
	}
	if _, ok := uc.mutation.F1(); !ok {
		return &ValidationError{Name: "f1", err: errors.New(`ent: missing required field "User.f1"`)}
	}
	if _, ok := uc.mutation.F2(); !ok {
		return &ValidationError{Name: "f2", err: errors.New(`ent: missing required field "User.f2"`)}
	}
	if _, ok := uc.mutation.F3(); !ok {
		return &ValidationError{Name: "f3", err: errors.New(`ent: missing required field "User.f3"`)}
	}
	if _, ok := uc.mutation.F4(); !ok {
		return &ValidationError{Name: "f4", err: errors.New(`ent: missing required field "User.f4"`)}
	}
	if _, ok := uc.mutation.F5(); !ok {
		return &ValidationError{Name: "f5", err: errors.New(`ent: missing required field "User.f5"`)}
	}
	if _, ok := uc.mutation.F6(); !ok {
		return &ValidationError{Name: "f6", err: errors.New(`ent: missing required field "User.f6"`)}
	}
	if _, ok := uc.mutation.F7(); !ok {
		return &ValidationError{Name: "f7", err: errors.New(`ent: missing required field "User.f7"`)}
	}
	if _, ok := uc.mutation.F8(); !ok {
		return &ValidationError{Name: "f8", err: errors.New(`ent: missing required field "User.f8"`)}
	}
	if _, ok := uc.mutation.F9(); !ok {
		return &ValidationError{Name: "f9", err: errors.New(`ent: missing required field "User.f9"`)}
	}
	if _, ok := uc.mutation.F10(); !ok {
		return &ValidationError{Name: "f10", err: errors.New(`ent: missing required field "User.f10"`)}
	}
	if _, ok := uc.mutation.F11(); !ok {
		return &ValidationError{Name: "f11", err: errors.New(`ent: missing required field "User.f11"`)}
	}
	if _, ok := uc.mutation.F12(); !ok {
		return &ValidationError{Name: "f12", err: errors.New(`ent: missing required field "User.f12"`)}
	}
	if _, ok := uc.mutation.F13(); !ok {
		return &ValidationError{Name: "f13", err: errors.New(`ent: missing required field "User.f13"`)}
	}
	if _, ok := uc.mutation.F14(); !ok {
		return &ValidationError{Name: "f14", err: errors.New(`ent: missing required field "User.f14"`)}
	}
	if _, ok := uc.mutation.F15(); !ok {
		return &ValidationError{Name: "f15", err: errors.New(`ent: missing required field "User.f15"`)}
	}
	if _, ok := uc.mutation.F16(); !ok {
		return &ValidationError{Name: "f16", err: errors.New(`ent: missing required field "User.f16"`)}
	}
	if _, ok := uc.mutation.F17(); !ok {
		return &ValidationError{Name: "f17", err: errors.New(`ent: missing required field "User.f17"`)}
	}
	if _, ok := uc.mutation.F18(); !ok {
		return &ValidationError{Name: "f18", err: errors.New(`ent: missing required field "User.f18"`)}
	}
	if _, ok := uc.mutation.F19(); !ok {
		return &ValidationError{Name: "f19", err: errors.New(`ent: missing required field "User.f19"`)}
	}
	if _, ok := uc.mutation.F20(); !ok {
		return &ValidationError{Name: "f20", err: errors.New(`ent: missing required field "User.f20"`)}
	}
	if _, ok := uc.mutation.F21(); !ok {
		return &ValidationError{Name: "f21", err: errors.New(`ent: missing required field "User.f21"`)}
	}
	if _, ok := uc.mutation.F22(); !ok {
		return &ValidationError{Name: "f22", err: errors.New(`ent: missing required field "User.f22"`)}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := uc.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uc.mutation.NickName(); ok {
		_spec.SetField(user.FieldNickName, field.TypeString, value)
		_node.NickName = value
	}
	if value, ok := uc.mutation.F1(); ok {
		_spec.SetField(user.FieldF1, field.TypeString, value)
		_node.F1 = value
	}
	if value, ok := uc.mutation.F2(); ok {
		_spec.SetField(user.FieldF2, field.TypeString, value)
		_node.F2 = value
	}
	if value, ok := uc.mutation.F3(); ok {
		_spec.SetField(user.FieldF3, field.TypeString, value)
		_node.F3 = value
	}
	if value, ok := uc.mutation.F4(); ok {
		_spec.SetField(user.FieldF4, field.TypeString, value)
		_node.F4 = value
	}
	if value, ok := uc.mutation.F5(); ok {
		_spec.SetField(user.FieldF5, field.TypeString, value)
		_node.F5 = value
	}
	if value, ok := uc.mutation.F6(); ok {
		_spec.SetField(user.FieldF6, field.TypeString, value)
		_node.F6 = value
	}
	if value, ok := uc.mutation.F7(); ok {
		_spec.SetField(user.FieldF7, field.TypeString, value)
		_node.F7 = value
	}
	if value, ok := uc.mutation.F8(); ok {
		_spec.SetField(user.FieldF8, field.TypeString, value)
		_node.F8 = value
	}
	if value, ok := uc.mutation.F9(); ok {
		_spec.SetField(user.FieldF9, field.TypeString, value)
		_node.F9 = value
	}
	if value, ok := uc.mutation.F10(); ok {
		_spec.SetField(user.FieldF10, field.TypeString, value)
		_node.F10 = value
	}
	if value, ok := uc.mutation.F11(); ok {
		_spec.SetField(user.FieldF11, field.TypeString, value)
		_node.F11 = value
	}
	if value, ok := uc.mutation.F12(); ok {
		_spec.SetField(user.FieldF12, field.TypeString, value)
		_node.F12 = value
	}
	if value, ok := uc.mutation.F13(); ok {
		_spec.SetField(user.FieldF13, field.TypeString, value)
		_node.F13 = value
	}
	if value, ok := uc.mutation.F14(); ok {
		_spec.SetField(user.FieldF14, field.TypeString, value)
		_node.F14 = value
	}
	if value, ok := uc.mutation.F15(); ok {
		_spec.SetField(user.FieldF15, field.TypeString, value)
		_node.F15 = value
	}
	if value, ok := uc.mutation.F16(); ok {
		_spec.SetField(user.FieldF16, field.TypeString, value)
		_node.F16 = value
	}
	if value, ok := uc.mutation.F17(); ok {
		_spec.SetField(user.FieldF17, field.TypeString, value)
		_node.F17 = value
	}
	if value, ok := uc.mutation.F18(); ok {
		_spec.SetField(user.FieldF18, field.TypeString, value)
		_node.F18 = value
	}
	if value, ok := uc.mutation.F19(); ok {
		_spec.SetField(user.FieldF19, field.TypeString, value)
		_node.F19 = value
	}
	if value, ok := uc.mutation.F20(); ok {
		_spec.SetField(user.FieldF20, field.TypeString, value)
		_node.F20 = value
	}
	if value, ok := uc.mutation.F21(); ok {
		_spec.SetField(user.FieldF21, field.TypeString, value)
		_node.F21 = value
	}
	if value, ok := uc.mutation.F22(); ok {
		_spec.SetField(user.FieldF22, field.TypeString, value)
		_node.F22 = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
